name: christopherrasker
favicon: null
layout_spectrum: 0.6497866110876203
typography_spectrum: 0.5901699147652835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.25131764030084014
  lightness: 0.3934118452016264
  saturation: 0.7066470901481807
  rhythmicContrast: 0.44230230362154543
purpose: []
